{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default attribute_base=ContentObjectAttribute}
{def $idstart="ContentObjectAttribute_"
     $idend=concat("_",$attribute.id)
     $event=$attribute.content
     }
{*$attribute.content|attribute(show)*}     
{ezscript_require( array('ezjsc::jquery', 'jquery-ui-1.8.9.custom.min.js', 'bcalendar.js') )}
{ezcss_require('blendcalendar.css')}

<div class="block bc-event-block">
    <div class="block bc-element-occurs">
        <label class="inline" for="{$idstart}recurtype{$idend}">Occurs:</label>
        <select class="bc-recurtype" name="{$idstart}recurtype{$idend}" id="{$idstart}recurtype{$idend}">
            <option value="ONCE" {if $event.recurrence_type|eq(1)}selected="selected" {/if}>Once</option>
            <option value="WEEK" {if $event.recurrence_type|eq(2)}selected="selected" {/if}>Every Week</option>
            <option value="MONTH" {if or($event.recurrence_type|eq(4),$event.recurrence_type|eq(8))}selected="selected" {/if}>Every Month</option>
            <option value="YEAR" {if or($event.recurrence_type|eq(16),$event.recurrence_type|eq(32))}selected="selected" {/if}>Every Year</option>
        </select>
    </div>
    <div class="bc-recurs">
        <div class="block bc-block-single bc-recurblock" {if $event.recurrence_type|ne(1)}style="display:none" {/if}>
            <label class="inline" for="{$idstart}singledate{$idend}">on</label>
            <input type="text"  name="{$idstart}singledate{$idend}" id="{$idstart}singledate{$idend}" class="bc-date"
                value="{if $event.recurrence_type|eq(1)}{$event.singledate}{else}{$event.range_start|datetime('custom','%n/%j/%Y')}{/if}"
            />
        </div>
        <div class="block bc-block-weekly bc-recurblock" {if $event.recurrence_type|ne(2)}style="display:none" {/if}>
            on
            <input type="checkbox" name="{$idstart}weekdays{$idend}[]" 
                id="{$idstart}weekdays{$idend}_0" value="0" {if $event.sunday}checked="checked"{/if} /> 
            <label class="inline" for="{$idstart}weekdays{$idend}_0" >Su</label>
            <input type="checkbox" name="{$idstart}weekdays{$idend}[]" 
                id="{$idstart}weekdays{$idend}_1" value="1" {if $event.monday}checked="checked"{/if} /> 
            <label class="inline" for="{$idstart}weekdays{$idend}_1">Mo</label>
            <input type="checkbox" name="{$idstart}weekdays{$idend}[]" 
                id="{$idstart}weekdays{$idend}_2" value="2" {if $event.tuesday}checked="checked"{/if} /> 
            <label class="inline" for="{$idstart}weekdays{$idend}_2">Tu</label>
            <input type="checkbox" name="{$idstart}weekdays{$idend}[]" 
                id="{$idstart}weekdays{$idend}_3" value="3" {if $event.wednesday}checked="checked"{/if} /> 
            <label class="inline" for="{$idstart}weekdays{$idend}_3">We</label>
            <input type="checkbox" name="{$idstart}weekdays{$idend}[]" 
                id="{$idstart}weekdays{$idend}_4" value="4" {if $event.thursday}checked="checked"{/if} /> 
            <label class="inline" for="{$idstart}weekdays{$idend}_4">Th</label>
            <input type="checkbox" name="{$idstart}weekdays{$idend}[]" 
                id="{$idstart}weekdays{$idend}_5" value="5" {if $event.friday}checked="checked"{/if} /> 
            <label class="inline" for="{$idstart}weekdays{$idend}_5">Fr</label>
            <input type="checkbox" name="{$idstart}weekdays{$idend}[]" 
                id="{$idstart}weekdays{$idend}_6" value="6" {if $event.saturday}checked="checked"{/if} /> 
            <label class="inline" for="{$idstart}weekdays{$idend}_6">Sa</label>
        </div>
        <div class="block bc-block-monthly bc-recurblock" {if and($event.recurrence_type|ne(4),$event.recurrence_type|ne(8))}style="display:none"{/if} >
            <div class="block">
                <input type="radio" name="{$idstart}monthrecurtype{$idend}" id="{$idstart}monthrecurtype{$idend}_static" {if $event.recurrence_type|eq(4)}checked="checked"{/if} value="MONTHSTATIC" />
                <label class="inline" for="{$idstart}monthrecurtype{$idend}_static">on the</label> 
                <select name="{$idstart}monthstaticrecurdate{$idend}">
                    {for 1 to 31 as $day}
                    {def $dt=makedate(1,$day,2001)}
                    <option value="{$day}" {if $event.day|eq($day)}selected="selected"{/if} >{$dt|datetime('custom','%j%S')}</option>
                    {/for}
                    {undef $dt}
                </select>
            </div>
            <div class="block">
                <input type="radio" name="{$idstart}monthrecurtype{$idend}" id="{$idstart}monthrecurtype{$idend}_relative" {if $event.recurrence_type|eq(8)}checked="checked"{/if}  value="MONTHRELATIVE" />
                <label class="inline" for="{$idstart}monthrelativeweek{$idend}">on the</label> 
                <select name="{$idstart}monthrelativeweek{$idend}" id="{$idstart}monthrelativeweek{$idend}">
                    <option {if $event.week|eq(1)}selected="selected" {/if} value="1" >First</option>
                    <option {if $event.week|eq(2)}selected="selected" {/if} value="2" >Second</option>
                    <option {if $event.week|eq(3)}selected="selected" {/if} value="3" >Third</option>
                    <option {if $event.week|eq(4)}selected="selected" {/if} value="4" >Fourth</option>
                    <!--<option {if $event.week|eq(-1)}selected="selected" {/if} value="-1" >Last</option>-->
                </select> 
                <select name="{$idstart}monthrelativeday{$idend}" id="{$idstart}monthrelativeday{$idend}">
                    <option value="0" {if $event.sunday}selected="selected" {/if}>Sunday</option>
                    <option value="1" {if $event.monday}selected="selected" {/if}>Monday</option>
                    <option value="2" {if $event.tuesday}selected="selected" {/if}>Tuesday</option>
                    <option value="3" {if $event.wednesday}selected="selected" {/if}>Wednesday</option>
                    <option value="4" {if $event.thursday}selected="selected" {/if}>Thursday</option>
                    <option value="5" {if $event.friday}selected="selected" {/if}>Friday</option>
                    <option value="6" {if $event.saturday}selected="selected" {/if}>Saturday</option>
                </select> of the month
            </div>
        </div>
        <div class="block bc-block-yearly bc-recurblock" {if and($event.recurrence_type|ne(16),$event.recurrence_type|ne(32))}style="display:none"{/if} >
            <div class="block">
                <input type="radio" name="{$idstart}yearrecurtype{$idend}" id="{$idstart}yearrecurtype{$idend}_static" {if $event.recurrence_type|eq(16)}checked="checked"{/if} value="YEARSTATIC" />
                <label class="inline" for="{$idstart}yearrecurtype{$idend}_static">on</label> 
                <select name="{$idstart}yearstaticrecurmonth{$idend}">
                    {for 1 to 12 as $month}
                    {def $dt=makedate($month, 1,2001)}
                    <option {if $event.month|eq($month)}selected="selected" {/if}value="{$month}">{$dt|datetime('custom', '%F')}</option>                
                    {/for}
                    {undef $dt}
                </select>
                <select name="{$idstart}yearstaticrecurdate{$idend}">
                    {for 1 to 31 as $day}
                    {def $dt=makedate(1,$day,2001)}
                    <option {if $event.day|eq($day)}selected="selected" {/if}value="{$day}">{$dt|datetime('custom','%j%S')}</option>
                    {/for}
                    {undef $dt}
                </select>
            </div>
            <div class="block">
                <input type="radio" name="{$idstart}yearrecurtype{$idend}" id="{$idstart}yearrecurtype{$idend}_relative" {if $event.recurrence_type|eq(32)}checked="checked"{/if} value="YEARRELATIVE" />
                <label class="inline" for="{$idstart}yearrelativeweek{$idend}">on the</label> 
                <select name="{$idstart}yearrelativeweek{$idend}" id="{$idstart}yearrelativeweek{$idend}">
                    <option {if $event.week|eq(1)}selected="selected" {/if} value="1" >First</option>
                    <option {if $event.week|eq(2)}selected="selected" {/if} value="2" >Second</option>
                    <option {if $event.week|eq(3)}selected="selected" {/if} value="3" >Third</option>
                    <option {if $event.week|eq(4)}selected="selected" {/if} value="4" >Fourth</option>
                    <!--<option {if $event.week|eq(-1)}selected="selected" {/if} value="-1" >Last</option>-->
                </select> 
                <select name="{$idstart}yearrelativeday{$idend}" id="{$idstart}yearrelativeday{$idend}">
                    <option value="0" {if $event.sunday}selected="selected" {/if}>Sunday</option>
                    <option value="1" {if $event.monday}selected="selected" {/if}>Monday</option>
                    <option value="2" {if $event.tuesday}selected="selected" {/if}>Tuesday</option>
                    <option value="3" {if $event.wednesday}selected="selected" {/if}>Wednesday</option>
                    <option value="4" {if $event.thursday}selected="selected" {/if}>Thursday</option>
                    <option value="5" {if $event.friday}selected="selected" {/if}>Friday</option>
                    <option value="6" {if $event.saturday}selected="selected" {/if}>Saturday</option>
                </select> in
                <select name="{$idstart}yearrelativemonth{$idend}">
                    {for 1 to 12 as $month}
                    {def $dt=makedate($month, 1,2001)}
                    <option {if $event.month|eq($month)}selected="selected" {/if}value="{$month}">{$dt|datetime('custom', '%F')}</option>                
                    {/for}
                </select>
                
            </div>
        </div>
    
        <div class="block bc-element-range" {if $event.recurrence_type|eq(1)}style="display:none" {/if}>
            <label for="{$idstart}interval{$idend}" class="inline">Repeat Every</label>
                <select name="{$idstart}interval{$idend}" id="{$idstart}interval{$idend}">
                    {for 1 to 10 as $interval}
                    <option {if $event.interval|eq($interval)}selected="selected" {/if}value="{$interval}">{$interval}</option>
                    {/for}
                </select>
                <span class="bc-repeat-type">{switch match=$event.recurrence_type}{case match=2}week(s){/case}{case match=array(4,8)}month(s){/case}{case match=array(16,32)}year(s){/case}{/switch}</span><br />
            
            <label class="inline" for="{$idstart}rangestart{$idend}">starting</label>
            <input type="text" name="{$idstart}rangestart{$idend}" id="{$idstart}rangestart{$idend}" class="bc-date" value="{$event.range_start|datetime('custom','%n/%j/%Y')}" /><br />
            
            <label class="inline" for="{$idstart}rangeend{$idend}">and continuing</label>
            
            <input type="radio" name="{$idstart}rangeendtype{$idend}" id="{$idstart}rangeendtype{$idend}_null" class="bc-rangeendtype-null" value="NULL" {if $event.range_end|not}checked="checked"{/if} />
            
            <label class="inline" for="{$idstart}rangeendtype{$idend}_null">forever</label>
            
            <input type="radio" name="{$idstart}rangeendtype{$idend}" id="{$idstart}rangeendtype{$idend}_date" class="bc-rangeendtype-date" value="DATE" {if $event.range_end}checked="checked"{/if} />
            <label class="inline" for="{$idstart}rangeendtype{$idend}_date">until</label>
            
            <input type="text" name="{$idstart}rangeend{$idend}" id="{$idstart}rangeend{$idend}"  {if $event.range_end|not}disabled="disabled"{/if} class="bc-date bc-rangeend-date" value="{$event.range_end|datetime('custom','%n/%j/%Y')}" />
        </div>
    </div><!-- .bc-recurs -->
    <div class="block bc-element-time">
        <strong>Time</strong><br />
        <label for="{$idstart}timestart{$idend}" class="inline">From:</label> 
        
        <input type="text" name="{$idstart}timestart{$idend}" id="{$idstart}timestart{$idend}" class="bc-time" 
            value="{$event.start_time_local}"
        />
        
        <label for="{$idstart}timestart{$idend}" class="inline">To</label> 
        <input type="text" name="{$idstart}timeend{$idend}" id="{$idstart}timeend{$idend}" class="bc-time" 
            value="{$event.end_time_local}"
        />
        
        <input type="checkbox" name="{$idstart}allday{$idend}" id="{$idstart}allday{$idend}" value="1" 
            {if $event.all_day}checked="checked"{/if}
        /> 
        
        <label class="inline" for="{$idstart}allday{$idend}">All Day</label>
    
    </div>


</div><!-- .block -->


{/default}